# Generated by Django 2.2.8 on 2021-05-24 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='evenement',
            new_name='evenementiel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titre',
        ),
        migrations.AddField(
            model_name='post',
            name='priorite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priorite', to='communitymanager.Priorite'),
        ),
    ]
