# Generated by Django 2.2.8 on 2021-05-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0002_auto_20210524_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
