# Generated by Django 2.2.8 on 2021-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0004_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
