# Generated by Django 2.2.8 on 2021-05-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210525_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='contenu',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_de_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
